# Generated by Django 5.1.4 on 2024-12-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_millionaire_alter_articles_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Millionaire',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
